config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :organization_users, OrganizationLogin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"

  resources :funding_needs do

  end
  #TODO: add interests model that will store
  #all the known interests
  #probably remove some of those fields from fields_of_interest
  get 'get_funding_needs' => 'funding_needs#get_funding_needs', as: 'get_funding_needs'

  get 'get_user_field_of_interests' => 'field_of_interests#get_user_field_of_interests', as: 'get_user_field_of_interests'

  post 'update_user_field_of_interest' => 'field_of_interests#update_user_field_of_interest', as: 'update_user_field_of_interest'

  get 'donor/login/:token' => 'donor_sessions#create', as: 'donor_login'
  delete 'donor/logout' => 'donor_sessions#destroy', as: 'donor_logout'

  post 'donor/request_session' => 'donor_sessions#request_new_session', as: 'donor_new_session'

end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :funding_needs
  has_many :distributions

  belongs_to :organization_user

  has_attached_file :image,
                    {styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: "/images/:style/missing.png",
                    :storage => :s3,
                    :s3_credentials => {:bucket => ENV['S3_CDN_BUCKET'], :access_key_id => ENV['S3_CDN_KEY_ID'], :secret_access_key => ENV['S3_CDN_SECRET'], s3_region: ENV['AWS_REGION']}}

  validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, :message => 'file type is not allowed (only jpeg/png/gif images)'
  
  def self.where_not_valid_organization_upload(header)
    return !(header.find_index("Organization Legal Name") &&
             header.find_index("Party ID") &&
             header.find_index("Tax ID") &&
             header.find_index("Email"))
  end
  
  def self.import_row(header, row)
    if where_not_valid_organization_upload(header)
      raise ArgumentError.new('Invalid data for this Organization upload type.')
    end

    name = row[header.find_index("Organization Legal Name")] if header.find_index("Organization Legal Name")
    external_id = row[header.find_index("Party ID")] if header.find_index("Party ID")
    ein = row[header.find_index("Tax ID")] if header.find_index("Tax ID")
    email = row[header.find_index("Email")] if header.find_index("Email")
    #TODO: map row based on header columns and attrs of organization
    return if external_id.nil?
    organization = Organization.find_by(:external_id => external_id)

    org_user = OrganizationUser.find_by(:email => email)
    if org_user.nil?
      pass = Passgen::generate(:length => 14)
      org_user = OrganizationUser.create(email: email, password: pass, password_confirmation: pass, name: email)
    else
      # if we are going to update the org_user. put it here...
      # org_user.update_attributes(...)
    end

    if organization
      organization.update_attributes(:email => email, :ein => ein, :name => name, organization_user_id: org_user.id)
    else
      Organization.create(:email => email, :ein => ein, :name => name, :external_id => external_id, organization_user_id: org_user.id)
    end
  end

  def stellar_search_url
     "https://dmf.iphiview.com/dmf/ManageMyFund/RecommendGrants/AddaGrantee/AddaGranteeResults/tabid/528/dispatch/enhancedcharitysearch_keywords%24#{self.ein}_exact%24True_me%24False_cce%24False/Default.aspx#dispatch=EnhancedCharitySearch_keywords%24#{self.ein}_exact%24True_me%24False_cce%24False"
  end
end

app/views/organizations/shared/_links.erb
<%- if controller_name != 'sessions' %>
    <% scope = Devise::Mapping.find_scope!(resource_name) %>
    <%= link_to t('active_admin.devise.links.sign_in'), send(:"new_#{scope}_session_path") %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to t('active_admin.devise.links.sign_up'), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
    <%= link_to t('active_admin.devise.links.forgot_your_password'), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to t('active_admin.devise.links.resend_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to t('active_admin.devise.links.resend_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
        <%= link_to t('active_admin.devise.links.sign_in_with_omniauth_provider', provider: provider.to_s.titleize),
                    omniauth_authorize_path(resource_name, provider) %><br />
    <% end -%>
<% end -%>