config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :organization_users, OrganizationLogin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"

  resources :funding_needs do

  end
  #TODO: add interests model that will store
  #all the known interests
  #probably remove some of those fields from fields_of_interest
  get 'get_funding_needs' => 'funding_needs#get_funding_needs', as: 'get_funding_needs'

  get 'get_user_field_of_interests' => 'field_of_interests#get_user_field_of_interests', as: 'get_user_field_of_interests'

  post 'update_user_field_of_interest' => 'field_of_interests#update_user_field_of_interest', as: 'update_user_field_of_interest'

  get 'donor/login/:token' => 'donor_sessions#create', as: 'donor_login'
  delete 'donor/logout' => 'donor_sessions#destroy', as: 'donor_logout'

  post 'donor/request_session' => 'donor_sessions#request_new_session', as: 'donor_new_session'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/views/home/_logged_in.html.erb
<div class="row">
  <nav id="preferenceContainer" class="col-md-3 d-none d-md-block bg-light sidebar" style="min-height: 500px;">
    <div class="sidebar-sticky">
      <div class="p-2">
        1) Select the causes you care about most
      </div>
      <div class="showbox" style="margin-top: 10px;">
        <div class="loader">
          <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
          </svg>
        </div>
      </div>
    </div>
  </nav>
  <main role="main" class="col-md-9">
    <div class="p-2">
      2) View projects related to the causes you selected
    </div>

    <div class="row">
      <div class="container card-group" id="interestContainer">
        <div class="showbox">
          <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
              <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
            </svg>
          </div>
        </div>
      </div>
    </div>  
  </main>
</div>

app/views/home/_not_logged_in.html.erb
<div class="position-relative overflow-hidden p-2 p-md-2 m-md-1 text-center bg-light">
  <div class="col-md-8 p-lg-8 mx-auto my-8">
    <h1 class="display-4 font-weight-normal">Welcome to <%= image_tag 'givedsm_text.png', style: "width: 283px; margin-top: -13px;" %></h1>
    <p class="lead font-weight-normal">We help connect donors with causes they care about.<br>GIVEdsm provides
      information on timely funding needs of charitable organizations impacting<br>Greater Des Moines.</p>

    <p class="lead font-weight-normal">Log in to discover opportunities to be Better Together.</p>

    <h3 style="margin-top: 20px">Enter your email and we'll send you a link to access GIVEdsm.</h3>
    <%= form_tag(donor_new_session_path, method: "post") do %>


        <%= text_field_tag :email, "", class: "form-control" %>
        <input type="submit" class="btn btn-primary" value="Send" style="margin-top: 10px;">
    <% end %>

    <% if notice %>
        <h4><%= notice %></h4>
    <% end %>
    <p></p>
    <p class="lead font-weight-normal">For assistance email us (<a href="mailto:biedenfeld@desmoinesfoundation.org">biedenfeld@desmoinesfoundation.org</a>) <br>or call (515) 883-2626.</p>
  </div>
</div>

app/views/home/index.html.erb
<% if current_donor %>
  <%= render partial: 'logged_in' %>
<% else %>
  <%= render partial: 'not_logged_in' %>
<% end %>