config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :organization_users, OrganizationLogin::Devise.config
  ActiveAdmin.routes(self)

  root to: "home#index"

  resources :funding_needs do

  end
  #TODO: add interests model that will store
  #all the known interests
  #probably remove some of those fields from fields_of_interest
  get 'get_funding_needs' => 'funding_needs#get_funding_needs', as: 'get_funding_needs'

  get 'get_user_field_of_interests' => 'field_of_interests#get_user_field_of_interests', as: 'get_user_field_of_interests'

  post 'update_user_field_of_interest' => 'field_of_interests#update_user_field_of_interest', as: 'update_user_field_of_interest'

  get 'donor/login/:token' => 'donor_sessions#create', as: 'donor_login'
  delete 'donor/logout' => 'donor_sessions#destroy', as: 'donor_logout'

  post 'donor/request_session' => 'donor_sessions#request_new_session', as: 'donor_new_session'

end

app/views/layouts/_card.html.erb
<% @funding_needs.each do |funding_need| %>
  <div class="card-container text-center flip p-2 d-flex flex-wrap">
    <div class="card box-shadow d-flex flex-wrap">
      <div class="face front">
        <div class="card-header card-field-header">
          <h3 class=""><%= funding_need.organization.name %></h3>
        </div>
        <div class="card-image-section">
          <% if Rails.env.production? %>
              <%= image_tag funding_need.image.url(:medium) %>
          <% else %>
              <img src="https://cdn.glitch.com/6a75ee71-9345-4dd6-ac44-5fb0d2c1d56a%2Fimage.png?1521776197497" alt="Card image"/>
          <% end %>
        </div>
        <div class="card-body toggle">
          <h2 class="pt-2"><bold> <%= funding_need.name %></bold> </h2>
          <% funding_need.interests.limit(5).each do |interest| %>
            <span class="badge badge-pill interest-color"><%= truncate(interest.name, length: 20) %></span>
          <% end %>
          </h4>
        </div>
      </div>
      <div class="face back">
        <div class="card-header card-field-header">
          <h3 class=""><%= funding_need.organization.name %></h3>
        </div>
        <div class="card-body">
          <h3 class="pt-2"><%= funding_need.name %></h3>
          <p class="pt-2"> <%= truncate(funding_need.description, :length => 350) %></p>
          <h3 class="brand-link"><%= link_to "Learn More", funding_need.get_web_link, target: "_blank" %></h3>
          <h3 class="pt-2">Funding Goal: <%= number_to_currency funding_need.goal, locale: :en, precision: 0 %></h3>
          <h6 class="pt-2">Funding Deadline: <%= funding_need.end_date.strftime("%B %e, %Y") %></h6>
          <a href="<%= funding_need.organization.stellar_search_url %>" class="btn btn-donate">Make a Grant</a>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_field_of_interest.html.erb
<div class="well">
  <div class="p-2">
    1) Select the causes you care about most
  </div>
  <% @combined_interests.each do |interest| %>
    <div  class="list-group-item" data-interest-id="<%= interest[:id] %>">
      <% label = if interest[:subcategory].present?
                   interest[:subcategory]
                 elsif interest[:category].present?
                   interest[:category]
                 else
                   interest[:name]
                 end
      %>

      <% if interest[:subcategory].present? %>
        <span style="padding-left: 15px;">
          <%=interest[:subcategory] %>
        </span>
      <% else %>
        <span style="font-weight: bold;">
          <%= interest[:category] %>
        </span>
      <% end %>
      <i class="fas fa-heart heart" style="float: right; <%= 'display:none;' unless interest[:liked] %>" ></i>
    </div>
  <% end %>
</div>

app/views/layouts/active_admin_organization_devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">

  <title><%= @page_title %></title>

  <% ActiveAdmin.application.stylesheets.each do |style, options| %>
      <%= stylesheet_link_tag style, options %>
  <% end %>
  <% ActiveAdmin.application.javascripts.each do |path| %>
      <%= javascript_include_tag path %>
  <% end %>

  <%= favicon_link_tag ActiveAdmin.application.favicon if ActiveAdmin.application.favicon %>

  <%= csrf_meta_tag %>
</head>
<body class="active_admin logged_out <%= controller.action_name %>">
<div id="wrapper">

  <div id="content_wrapper">
    <% if flash_messages.any? %>
        <% flash_messages.each do |type, message| %>
            <%= content_tag :div, message, :class => "flash flash_#{type}" unless message.nil? or message.empty? %>
        <% end %>
    <% end %>
    <div id="active_admin_content">
      <%= yield %>
    </div>
  </div>
  <div id="footer">
    <%= yield :footer %>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Community Foundation</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css'>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css'>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>




<body>
  <header>





    <nav class="navbar brand-bar sticky-top flex-md-nowrap p-1">
      <%= image_tag("Givedsmheader2.png", :class => "brand-logo navbar-brand mr-0") %>
      <% if current_donor %>
        <input id="interest-search" class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <% end %>
      <ul class="navbar-nav px-3">
        <% if current_donor %>
          <% if current_organization_user %>
            <li class="nav-item text-nowrap">
              <%= link_to "My Org", "/myorg" %>
            </li>
            <li class="nav-item text-nowrap">
              <%= link_to "Donor Log out", donor_logout_path, method: :delete %>
            </li>
          <% else %>
            <li class="nav-item text-nowrap">
              <%= link_to "Log out", donor_logout_path, method: :delete %>
            </li>
          <% end %>
        <% else %>
          <li class="nav-item text-nowrap">
            <%= link_to "My Org", "/myorg" %>
          </li>
        <% end %>
      </ul>
    </nav>
  </header>

  <div class="container-fluid">
    <%= yield %>
  </div>
</body>

</html>